apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wa-bot
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Kelompok-1-ODP-IT-343/bot-wa-kpr.git
    targetRevision: main
    path: k3s
  destination:
    server: https://kubernetes.default.svc
    namespace: griya-app-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
      - Validate=true
      - ApplyOutOfSyncOnly=true
  revisionHistoryLimit: 5
