apiVersion: v1
kind: Service
metadata:
  name: wa-bot
  namespace: griya-app-prod
spec:
  selector:
    app: wa-bot
  ports:
    - name: http
      port: 9090
      targetPort: 9090
      nodePort: 30010   
  type: NodePort        
