name: ci-dockerhub

on:
  push:
    branches: ["main"]
    tags: ["v*", "release-*"]
  workflow_dispatch:

env:
  IMAGE_NAME: bot-wa-kpr

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repo
      - uses: actions/checkout@v4

      # Step 2: Setup Docker Buildx
      - uses: docker/setup-buildx-action@v3

      # Step 3: Login ke Docker Hub
      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Step 4: Generate tag otomatis
      - name: Generate tags
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest,enable=${{ startsWith(github.ref, 'refs/heads/main') }}
            type=sha,format=long,prefix=sha-
            type=ref,event=tag

      # Step 5: Build dan push image
      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # (Opsional) Tampilkan hasil tag
      - name: Show pushed tags
        run: |
          echo "Pushed tags:"
          echo "${{ steps.meta.outputs.tags }}"
