name: ci-dockerhub

on:
  push:
    branches: ["main"]
    tags: ["v*", "release-*"]
  workflow_dispatch:

env:
  IMAGE_NAME: bot-wa-kpr

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repo
      - uses: actions/checkout@v4

      # Step 2: Setup Docker Buildx
      - uses: docker/setup-buildx-action@v3

      # Step 3: Login ke Docker Hub
      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Step 4: Generate tag otomatis
      - name: Generate tags
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest,enable=${{ startsWith(github.ref, 'refs/heads/main') }}
            type=sha,format=long,prefix=sha-
            type=ref,event=tag

      # Step 5: Build dan push image
      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # (Opsional) Tampilkan hasil tag
      - name: Show pushed tags
        run: |
          echo "Pushed tags:"
          echo "${{ steps.meta.outputs.tags }}"

      - name: Get SHA Tag
        id: image
        run: |
          TAG=$(echo "${{ steps.meta.outputs.tags }}" | grep 'sha-' | head -n 1)
          echo "sha_tag=$TAG" >> $GITHUB_OUTPUT
          echo "Using tag: $TAG"

      # --- TRIVY SCAN (SIMPLE & CLEAR) ---
      - name: Trivy Scan
        id: trivy
        uses: aquasecurity/trivy-action@0.24.0
        with:
          # Jika menggunakan Latest
          image-ref: docker.io/satuatap/bot-wa-kpr:latest
          # Jika mengggunakan SHA
          # image-ref: ${{ steps.image.outputs.sha_tag }}
          format: 'table'
          vuln-type: 'os,library'
          severity: 'HIGH,CRITICAL'
          exit-code: '0'
          ignore-unfixed: false
          output: trivy-report.txt

      # --- GITHUB SUMMARY (CLEAR) ---
      - name: Upload Trivy Summary
        run: |
          echo "## ðŸ” Trivy Vulnerability Scan Report" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY

          echo "**Image scanned:**" >> $GITHUB_STEP_SUMMARY
          echo "\`${{ steps.image.outputs.sha_tag }}\`" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY

          echo "### ðŸ“„ Full Trivy Report" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          cat trivy-report.txt >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
